### ISSUE TITLE
async is a reserved word in python 3.7 and shouldn't be used as a keyword argument

### ISSUE THREAD

**Issue by phdesign** [alexis-mignon/python-flickr-api#105]
`upload.py` accepts a keyword argument `async`, however this is now a reserved word in python 3. Suggest renaming it to `asynchronous`.

**Comment by mtrovo** [comment]
I added the option to provide a parameter `asynchronous` as a alias of `async`.

I released it on a new version so please make sure to update your dependency and test it again.
