### ISSUE TITLE
Save adds extensions even when provided

### ISSUE THREAD

**Issue by mtrovo** [alexis-mignon/python-flickr-api#109]
Save API changed in an incompatible way as pointed here beaufour/flickr-download#48.

There are valid reasons to provide a whole filename instead of just the name part and we should support it. 

Right now I think the best solution should be:
- when an extension is provided, use it.
- when no extension is provided, use the default one based on the source page.

Examples:
- when source is `1234.jpg`, calling `save('abcd.jpg')` will create file `abcd.jpg`
- when source is `1234.jpg`, calling `save('abcd.mp4')` will create file `abcd.mp4`
- when source is `1234.jpg`, calling `save('abcd')` will create file `abcd.jpg`

**Comment by beaufour** [comment]
@alexis-mignon / @mtrovo any chance for a new release that includes this? I'm depending on the fix for my project.

**Comment by beaufour** [comment]
Any chance of a new release with this fix in it?

**Comment by alexis-mignon** [comment]
@beaufour Would you like to become maintainer on this projet ? Since I don't have much time to take care of it ?

**Comment by beaufour** [comment]
> @beaufour Would you like to become maintainer on this projet ? Since I don't have much time to take care of it ?

It's nice of you to ask, but I can't say I have a ton of time either so I think it would be "false advertising" if I were to pretend to be a maintainer... it depends on how busy the project is I guess? If it's only the odd request now and again I guess I could do it.

**Comment by alexis-mignon** [comment]
It's usually only a few requests every now and then indeed. Usually accespting some pull requests and uploading a new version once a few have been accepted.

And it's much better if maintainers actively use the project which is unfortunately not my case anymore. This means it rakes me even more time to get back into it when I need to. So it would really be a pleasure.

If you can indicate me an Id on PyPi I can register you as a maintener there too, so you can release new versions.

**Comment by beaufour** [comment]
Ok. Let's try then :) I'm "beaufour" on PyPi
