### ISSUE TITLE
Unauthorized Error 401 when I try to set the authorization verifier

### ISSUE THREAD

**Issue by mhossameldin** [alexis-mignon/python-flickr-api#46]
Hello

I was following the tutorial provided on the git repositery to start working with flickr_api

It was going fine until I wanted to set the verifier for the authorization handler.

I followed the steps and copied the code from the <oauth_verifier> tag, but I got the following error.

Keeping in mind that i am using the latest version of flickr_api

> > > runfile('C:/Users/Mahmoud/Documents/Python Scripts/getImages.py', wdir=r'C:/Users/Mahmoud/Documents/Python Scripts')
> > > runfile('C:/Users/Mahmoud/Documents/Python Scripts/getImages.py', wdir=r'C:/Users/Mahmoud/Documents/Python Scripts')
> > > https://www.flickr.com/services/oauth/authorize?oauth_token=72157644795843302-08e10638e37118fe&perms=read
> > > runfile('C:/Users/Mahmoud/Documents/Python Scripts/getImages.py', wdir=r'C:/Users/Mahmoud/Documents/Python Scripts')
> > > https://www.flickr.com/services/oauth/authorize?oauth_token=72157644808317325-3b1847232bd3d89f&perms=read
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "C:\Anaconda\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 540, in runfile
> > >     execfile(filename, namespace)
> > >   File "C:/Users/Mahmoud/Documents/Python Scripts/getImages.py", line 15, in <module>
> > >     a.set_verifier("e1b5dd87477f16b1")
> > >   File "C:\Anaconda\lib\site-packages\flickr_api\auth.py", line 141, in set_verifier
> > >     resp = urllib2.urlopen(req.to_url())
> > >   File "C:\Anaconda\lib\urllib2.py", line 127, in urlopen
> > >     return _opener.open(url, data, timeout)
> > >   File "C:\Anaconda\lib\urllib2.py", line 410, in open
> > >     response = meth(req, response)
> > >   File "C:\Anaconda\lib\urllib2.py", line 523, in http_response
> > >     'http', request, response, code, msg, hdrs)
> > >   File "C:\Anaconda\lib\urllib2.py", line 448, in error
> > >     return self._call_chain(_args)
> > >   File "C:\Anaconda\lib\urllib2.py", line 382, in _call_chain
> > >     result = func(_args)
> > >   File "C:\Anaconda\lib\urllib2.py", line 531, in http_error_default
> > >     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
> > > urllib2.HTTPError: HTTP Error 401: Unauthorized

**Comment by nigelb** [comment]
Hi,

Just a snippet of code to demonstrate the solution to people who arrive here and are still scratching their heads:

> import flickr_api
> 
> flickr_api.set_keys(api_key = 'my_api_key', api_secret = 'my_secret')
> a = flickr_api.auth.AuthHandler()
> url = a.get_authorization_url("read")
> print url
> verifier = raw_input("Verifier code: ")
> 
> a.set_verifier(verifier)
> a.save("flickr_credentials.dat")

1. Run the code.
2. Paste the displayed URL into a browser and accept the permission request.
3. Copy the `oauth_verifier` field and paste it into the terminal at the "Verifier code: " prompt.

This should result in the creation of the `flickr_credentials.dat` credential file which can be used like this:
> import flickr_api
> 
> flickr_api.set_keys(api_key = 'my_api_key', api_secret = 'my_secret')
> flickr_api.set_auth_handler("flickr_credentials.dat")
> user = flickr_api.test.login()
> print user.getPhotosets()

Hope this helps.
