### ISSUE TITLE
flickr_api.method_call.call_api(method = "flickr.photos.getInfo",photo_id = photoid) results in error after sometime

### ISSUE THREAD

**Issue by sharathchandra92** [alexis-mignon/python-flickr-api#51]
Hi,

I am trying to download tags associated with images. There are more than 3000 images. The above-mentioned call fails after 10-15 images. Is there any way I can correct this? By using some random seed etc while calling the function?

The same happens even for getPulblicList method for people's photos. Please let me know how this can be addressed.

Thanks,
Sharath Chandra

**Comment by abhiguru** [comment]
What was the reason ? Can the code be shared here ?
