### ISSUE TITLE
Getting Past the 10,000th Page

### ISSUE THREAD

**Issue by abhillman** [alexis-mignon/python-flickr-api#54]
Thanks for your time! This is not an issue with this library, per se, but appears to be a limitation or bug with the flickr API itself. When attempting to fetch a page number greater than 10,000 the API always returns the 10,000th page. For example:

```
>>> flickr_api.Person.findByUrl('https://www.flickr.com/people/britishlibrary/')
Person(id='12403504@N02', username='The British Library...)
>>> person=flickr_api.Person.findByUrl('https://www.flickr.com/people/britishlibrary/')
>>> person.getPhotos(per_page=1)
[Photo(id='11065529663', title='Image taken from pa...)];Info(page=1, perpage=1, pages=1023705, total=1023705)
>>> person.getPhotos(per_page=1, page=20000)      
[Photo(id='11062847324', title='Image taken from pa...)];Info(page=10000, perpage=1, pages=1023705, total=1023705)
```

Has anyone found a way to work around this? Thanks!

**Comment by alexis-mignon** [comment]
From memory, flickr allows to use their api to test from web forms. Would be interested to check if t's the case their too and if so, report the bug to them.

**Comment by charlesreid1** [comment]
If you change your perpage variable to 100, the 10,000-page maximum is now a 1,000,000 total photo maximum. The inherent limit in the number of photos Flickr will return is 1,000,000 photos.

**Comment by alexis-mignon** [comment]
Thanks @charlesreid1 for the explanation
