### ISSUE TITLE
Example dealing with pages

### ISSUE THREAD

**Issue by charlesreid1** [alexis-mignon/python-flickr-api#55]
Hi there,

Thanks for writing this library. I had one suggestion, and that is, to add an example that shows users how to deal with pages when Flickr returns multi-page results. Basically just showing the use of the arguments ```per_page``` and ```page``` for the ```getPhotos()``` method. It took me a while to figure out how to paginate through results, and documentation of those options would have helped.

**Comment by AlexisMignon** [comment]
There is a Walker which is designed to avoid to have to manually deal with pages:
```python
w = Walker(Photo.search, tags="animals")
for photo in w:
    print photo.title
```

It would indeed maybe a good idea to show an example in the Wiki

**Comment by alexis-mignon** [comment]
I added an example in the Wiki. Does the walker replies to your problem ?

**Comment by charlesreid1** [comment]
Yes, just gave it a try and it greatly simplified my code. Thanks for the wiki update and the example code!
