### ISSUE TITLE
Retrieve photo view count

### ISSUE THREAD

**Issue by vahidk** [alexis-mignon/python-flickr-api#59]
I'm trying to use flickr-api to extract view count information from [flickr100m dataset]  (http://yahoolabs.tumblr.com/post/89783581601/one-hundred-million-creative-commons-flickr-images):

My code looks something like this:
```
flickr_api.set_keys(api_key = flickr.API_KEY, api_secret = flickr.API_SECRET)
a = flickr_api.auth.AuthHandler.load('flickr_api_auth.txt')
flickr_api.set_auth_handler(a)
date = datetime.date.today()
photo = flickr_api.Photo(id=pp_id, secret=pp_secret)
stats = photo.getStats(date)
```

Calling getStats though returns an error:
```
flickr_api.flickrerrors.FlickrAPIError: 1 : User does not have stats
```

Is this the right of using the api? what's the problem here?

**Comment by alexis-mignon** [comment]
I'm very sorry for the late answer. I don't think the problem comes from the API. In case of doubts, I suggest to use the flickr api directly through the API explorer, for instance for [flickr.stats.getPhotoStats](https://www.flickr.com/services/api/explore/flickr.stats.getPhotoStats)
