### ISSUE TITLE
No module named setuptools

### ISSUE THREAD

**Issue by kkro** [alexis-mignon/python-flickr-api#61]
root@raspiv1x91:~# git clone https://github.com/alexis-mignon/python-flickr-api.git
Cloning into 'python-flickr-api'...
remote: Counting objects: 372, done.
remote: Total 372 (delta 0), reused 0 (delta 0), pack-reused 372
Receiving objects: 100% (372/372), 256.18 KiB | 460 KiB/s, done.
Resolving deltas: 100% (211/211), done.
root@raspiv1x91:~# cd python-flickr-api/
root@raspiv1x91:~/python-flickr-api# python setup.py install --user
Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    from setuptools import setup
ImportError: No module named setuptools
root@raspiv1x91:~/python-flickr-api#

**Comment by alexis-mignon** [comment]
Hello,

There is no setuptools on your pythonpath. So either you need to install the package using your package manager or pip. Either the pythonpath points to only a limited set of modules because you use the root account.

Best regards.

Alexis
