### ISSUE TITLE
Upload From URL

### ISSUE THREAD

**Issue by interpegasus** [alexis-mignon/python-flickr-api#67]
Hi, I would like to know how to upload to flickr via a fileobject or URL instead of passing a path to the photo file?

Reference:
`flickr_api.upload(photo_file = "path_to_the_photo_file", title = "My title")`

`photo_file = urllib.urlopen(photo_url)`

Thanks

**Comment by interpegasus** [comment]
It is possible via the last version, by passing the parameter: photo_file_data

Although it still requires the 'path_to_the_photo_file' parameter.

A pull request will be added to make 'path_to_the_photo_file' optional and pass only the  photo_file_data parameter.

Cheers!

**Comment by alexis-mignon** [comment]
I think I finally understood your concern. You can just give any file name you want to "photo_file" if you use 'photo_file_data'. This is required by the http POST" protocole.

**Comment by alexis-mignon** [comment]
I have added some examples in the tutorial.
