### ISSUE TITLE
Authorization steps not working

### ISSUE THREAD

**Issue by dkirkby** [alexis-mignon/python-flickr-api#72]
I am following the steps described in the tutorial and everything goes fine until I call the `set_verifier` method, and it tries to access https://www.flickr.com/services/oauth/access_token:

```
  File "/Users/david/anaconda/lib/python2.7/site-packages/flickr_api/auth.py", line 141, in set_verifier
    resp = urllib2.urlopen(req.to_url())
...
urllib2.HTTPError: HTTP Error 401: Unauthorized
```

Are the instructions still valid?

**Comment by dkirkby** [comment]
If I access the same URL that `auth.py` uses, including all its params, the response includes:
```
oauth_problem=signature_invalid
```
I also compared with the example URL [here]() and noticed that you don't explicitly specify:
```
&oauth_version=1.0
```
Could that be a problem?

**Comment by dkirkby** [comment]
I also noticed that the `oauth_token` you send does not match the one provided with the `oauth_verifier` from the previous step, unlike in the example [here](https://www.flickr.com/services/api/auth.oauth.html).

**Comment by dkirkby** [comment]
I am able to complete the authorization sequence and get an access token using requests_oauthlib and following [this gist](https://gist.github.com/blairg23/dc421453b035321a5e27), so it looks like the problem here is related to how requests are signed.  This package looks like a great wrapper of the flickr API, so its too bad that it is no longer working.

**Comment by tomquirk** [comment]
@dkirkby - it is still definitely working. I think there is caching happening somewhere that caches the `oauth-token`. Basically, if you mess up the steps on your first go and retry, the `oauth_token` is not updated, meaning the new `oauth_verifier` is mismatched/invalid.

If you start from scratch in another environment it should work (did for me at least).

**Comment by alexis-mignon** [comment]
Since nobody could replicate the problem, I close the issue. Reopen it if needed.
