### ISSUE TITLE
Link to Google Code still exists

### ISSUE THREAD

**Issue by Flimm** [alexis-mignon/python-flickr-api#73]
The GitHub blurb of this repo includes a link to the Google Code project:

![screen shot](https://cloud.githubusercontent.com/assets/355454/20802677/11d9eb50-b7ed-11e6-9a4d-272fa95cac8d.png)

Since Google Code is now merely an archive, maybe it would be good to remove the link too.

**Comment by tomquirk** [comment]
@alexis-mignon would you like to update this?

**Comment by Flimm** [comment]
Great, thanks! The link in `setup.py` is fixed, but not the GitHub blurb yet.

**Comment by tomquirk** [comment]
Yup, @alexis-mignon is the only one that can do that 😄
