### ISSUE TITLE
Would a Python 3 port be accepted?

### ISSUE THREAD

**Issue by Flimm** [alexis-mignon/python-flickr-api#75]
I could spend some time porting this to Python 2 and 3 together. So far, none of my pull requests have been responded to, so I'm not optimistic that if I spend time on this, the pull request would actually be accepted.

Would a port be accepted?

**Comment by Flimm** [comment]
This repo hasn't seen a commit in two years, would any pull requests at all be looked at and accepted?

**Comment by tomquirk** [comment]
PR #76 merged - Python 3 now supported! 🎉

**Comment by Flimm** [comment]
Yay! Thank you so much!
