### ISSUE TITLE
Guide for Create a Photoset

### ISSUE THREAD

**Issue by m4nn4** [alexis-mignon/python-flickr-api#77]
Hi, 

I'm trying to create automatically a phtoset witch flick_api :
I use the following code 
photoset = flickr_api.Photoset.create(title = album, primary_photo = basename)

album is the name of the album and basename is the name of a photo I already upload.

I have the following error code 
Traceback (most recent call last):
  File "./send_flickr.py", line 33, in <module>
    photoset = flickr_api.Photoset.create(title = album, primary_photo = basename)
  File "/opt/lib/python2.7/site-packages/flickr_api/reflection.py", line 286, in static_call
    method_args, format_result = method(*args, **kwargs)
  File "/opt/lib/python2.7/site-packages/flickr_api/objects.py", line 1504, in create
    pphoto_id = pphoto.id
AttributeError: 'str' object has no attribute 'id'

How do I use the flickr_api.Photoset.create ?
What's wrong ?

Regards
Mana

**Comment by tomquirk** [comment]
Hey @m4nn4,

You'll have to provide a `Photo()` instance as the _primary_photo_. Off the top of my head, you can get one of these from:
* flickr_api.upload
* <Photoset>.getPhotos()
* user.getPhotos()

I'll make sure to document this better in the wiki, thanks for the question!

**Comment by tomquirk** [comment]
I've added a note to that section of the [wiki](https://github.com/alexis-mignon/python-flickr-api/wiki/API-Reference#managing-photosets-aka-albums).
