### ISSUE TITLE
How to get image info given its url?

### ISSUE THREAD

**Issue by gombru** [alexis-mignon/python-flickr-api#86]
Hi,

I need to get image metadata given image URL. I have seen that flickr.reflection.getMethodInfo(method_name="flickr.photos.getInfo") can do what I want. But how can I call this method?

**Comment by alexis-mignon** [comment]
Hello,

Sorry for the last reply.

There are two ways to retrieve informations from a picture:

```python
import flickr_api
p = flickr_api.Photo(id="xxxxxxxxx")
p.getInfo()
```
or 

```python
from flickr_api.api import flickr
flickr.photos.getInfo(photo_id="xxxxxxxxx")
```
