### ISSUE TITLE
Photo upload on Windows not working

### ISSUE THREAD

**Issue by fgs22002** [alexis-mignon/python-flickr-api#87]
I'm having weird problems with uploading photos on Windows. My python script works smoothly on Ubuntu (16.04 LTS), but when I try to use it on Windows (with the same photo) I always get the exception '**5 : Filetype was not recognised**'

**Comment by alexis-mignon** [comment]
Hello,

Sorry for the late reply.

Could you provide more information about your problem or ideally prepare a small example that triggers the problems.

The few tests I did on Windows raised no problem.

Alexis
