### ISSUE TITLE
iter() returned non-iterator of type

### ISSUE THREAD

**Issue by newpro** [alexis-mignon/python-flickr-api#97]
Hey guys. Thanks very much for put together this amazing and convenient OO libraries! It saves me a lot of time in my research.

The [walker iter function](https://github.com/alexis-mignon/python-flickr-api/blob/master/flickr_api/objects.py#L2130) return itself instead of the list, this causes the titled error raised. An example is given as the following code:

```python
walker = flickr_api.Walker(flickr_api.Photo.search, text='football')
for p in walker:
    print (p.title)

# raise error: TypeError: iter() returned non-iterator of type 'Walker'
```

A relative read of the issue is [here](https://help.semmle.com/wiki/display/PYTHON/__iter__+method+returns+a+non-iterator).

Cheers!

**Comment by newpro** [comment]
hey @mtrovo , thx for reply!

I digged a little bit, you are right, the implementation should work for python 3, all it need to iterate is __init__, __iter__ and __next__. I try clone directly from master, it works fine, same for direct downloading from release version(0.6.1). However, if I directly pip it, and went into system package directory, I notice pip gives me a version that does not have [__next__ redirect to next()](https://github.com/alexis-mignon/python-flickr-api/blob/master/flickr_api/objects.py#L2142). Which I assume causes the above problem. 

I am using pip within conda, I am not sure if it actually download package differently from normal pip. The system info are as following:
>>> print(sys.version)
3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0]

Cheers!

**Comment by mtrovo** [comment]
I released a new version of the library, if could try using the new version. I will mark this issue as solved but feel free to reopen if you still have any problems.
